package main

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The tests in this file run the gate against a real git repository built
// in a temporary directory, with fixture coverage profiles.

// headProfile covers every statement on the feature branch except New.
const headProfile = `mode: set
example.com/m/pkg/a.go:3.14,5.2 1 1
example.com/m/pkg/a.go:7.14,9.2 1 1
example.com/m/pkg/new.go:3.16,5.2 1 1
example.com/m/pkg/new.go:7.16,9.2 1 0
example.com/m/pkg/u.go:3.14,5.2 1 1
example.com/m/pkg/gen.go:3.14,5.2 1 0
example.com/m/pkg/é.go:3.14,5.2 1 1
example.com/m/cmd/x/main.go:3.13,5.2 1 0
`

func gitIn(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	p := filepath.Join(dir, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(p), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

// newRepo makes a repository whose main branch holds pkg/a.go, pkg/old.go
// and cmd/x/main.go. Its git config sets options that would break a naive
// diff parser.
func newRepo(t *testing.T) string {
	t.Helper()
	t.Setenv("GIT_CONFIG_GLOBAL", os.DevNull)
	t.Setenv("GIT_CONFIG_NOSYSTEM", "1")
	for _, k := range []string{"GIT_AUTHOR", "GIT_COMMITTER"} {
		t.Setenv(k+"_NAME", "Test")
		t.Setenv(k+"_EMAIL", "test@example.com")
	}
	dir := t.TempDir()
	gitIn(t, dir, "init", "-q", "-b", "main")
	for _, kv := range [][2]string{{"diff.noprefix", "true"}, {"color.diff", "always"}, {"diff.relative", "true"}} {
		gitIn(t, dir, "config", kv[0], kv[1])
	}
	writeFile(t, dir, "go.mod", "module example.com/m\n")
	writeFile(t, dir, "pkg/a.go", "package pkg\n\nfunc A() int {\n\treturn 1\n}\n")
	writeFile(t, dir, "pkg/old.go", "package pkg\n\nfunc Old() int {\n\treturn 3\n}\n")
	writeFile(t, dir, "cmd/x/main.go", "package main\n\nfunc main() {\n\tprintln()\n}\n")
	gitIn(t, dir, "add", "-A")
	gitIn(t, dir, "commit", "-q", "-m", "base")
	return dir
}

// addFeature branches off main and changes, renames, adds and generates
// files, some committed and some not.
func addFeature(t *testing.T, dir string) {
	t.Helper()
	gitIn(t, dir, "checkout", "-q", "-b", "feature")
	writeFile(t, dir, "pkg/a.go", "package pkg\n\nfunc A() int {\n\treturn 1\n}\n\nfunc B() int {\n\treturn 2\n}\n")
	gitIn(t, dir, "mv", "pkg/old.go", "pkg/new.go")
	writeFile(t, dir, "pkg/new.go", "package pkg\n\nfunc Old() int {\n\treturn 3\n}\n\nfunc New() int {\n\treturn 4\n}\n")
	// A name git C-quotes in diff headers.
	writeFile(t, dir, "pkg/é.go", "package pkg\n\nfunc E() int {\n\treturn 6\n}\n")
	writeFile(t, dir, "cmd/x/main.go", "package main\n\nfunc main() {\n\tprintln(1)\n}\n")
	gitIn(t, dir, "add", "-A")
	gitIn(t, dir, "commit", "-q", "-m", "feature")
	// Untracked, and so new in full.
	writeFile(t, dir, "pkg/u.go", "package pkg\n\nfunc U() int {\n\treturn 5\n}\n")
	writeFile(t, dir, "pkg/gen.go", "// Code generated by hand. DO NOT EDIT.\n\npackage pkg\n\nfunc G() int {\n\treturn 7\n}\n")
	writeFile(t, dir, "cover.out", headProfile)
}

// baseFixture writes a baseline profile and returns a -test command that
// copies it into place.
func baseFixture(t *testing.T, profile string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "base.out")
	writeFile(t, filepath.Dir(p), "base.out", profile)
	return "cp " + p + " {profile}"
}

func newGate(dir string, actions bool) (gate, *bytes.Buffer) {
	var out bytes.Buffer
	return gate{root: dir, out: &printer{w: &out, actions: actions}, stderr: io.Discard}, &out
}

// basePct50 has A covered and Old not: 50%.
const basePct50 = "mode: set\nexample.com/m/pkg/a.go:3.14,5.2 1 1\nexample.com/m/pkg/old.go:3.16,5.2 1 0\n"

func TestCheckMeasuresChangedLinesInARepo(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	test := baseFixture(t, basePct50)
	for _, tc := range []struct {
		min  float64
		want bool
	}{{80, false}, {70, true}} {
		g, out := newGate(dir, false)
		ok, err := g.check(config{profile: "cover.out", base: "main", min: tc.min, test: test})
		if err != nil {
			t.Fatal(err)
		}
		if ok != tc.want {
			t.Errorf("min %.0f: ok = %v, want %v\n%s", tc.min, ok, tc.want, out)
		}
		// a.go 7-9, u.go 3-5 and é.go 3-5 ran; new.go 7-9 did not. cmd/,
		// gen.go and unchanged lines don't count.
		if !strings.Contains(out.String(), "9 of 12 covered") {
			t.Errorf("min %.0f: want 9 of 12 changed lines covered\n%s", tc.min, out)
		}
		if !strings.Contains(out.String(), "merge base") || !strings.Contains(out.String(), "50.00%") {
			t.Errorf("min %.0f: want the 50%% baseline reported\n%s", tc.min, out)
		}
	}
	g, out := newGate(dir, false)
	if _, err := g.check(config{profile: "cover.out", base: "main", min: 80, test: test}); err != nil {
		t.Fatal(err)
	}
	for _, l := range []string{"pkg/new.go:7", "pkg/new.go:8", "pkg/new.go:9"} {
		if !strings.Contains(out.String(), "  "+l+"\n") {
			t.Errorf("want %s listed as uncovered\n%s", l, out)
		}
	}
}

func TestCheckFailsWhenTotalDrops(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	full := "mode: set\nexample.com/m/pkg/a.go:3.14,5.2 1 1\nexample.com/m/pkg/old.go:3.16,5.2 1 1\n"
	g, out := newGate(dir, false)
	ok, err := g.check(config{profile: "cover.out", base: "main", min: 0, test: baseFixture(t, full)})
	if err != nil {
		t.Fatal(err)
	}
	if ok || !strings.Contains(out.String(), "dropped by 16.67 points") {
		t.Fatalf("ok = %v, want a failure for the drop from 100%% to 83.33%%\n%s", ok, out)
	}
}

func TestCheckSkipsWhenNothingChanged(t *testing.T) {
	dir := newRepo(t)
	g, out := newGate(dir, true)
	ok, err := g.check(config{profile: "cover.out", base: "main", min: 80})
	if err != nil || !ok {
		t.Fatalf("ok = %v, err = %v; want a skip", ok, err)
	}
	if !strings.HasPrefix(out.String(), "::warning ") || !strings.Contains(out.String(), "no measured Go changes") {
		t.Fatalf("want a warning annotation, got %q", out)
	}
}

func TestCheckMissingBase(t *testing.T) {
	dir := newRepo(t)
	g, out := newGate(dir, false)
	ok, err := g.check(config{base: "origin/nope"})
	if err != nil || !ok || !strings.Contains(out.String(), "base origin/nope not found; skipping") {
		t.Fatalf("ok = %v, err = %v, out %q; want a skip", ok, err, out)
	}
	g, _ = newGate(dir, false)
	if _, err := g.check(config{base: "origin/nope", requireBase: true}); err == nil || !strings.Contains(err.Error(), "fetch-depth") {
		t.Fatalf("got %v, want an error with -require-base", err)
	}
}

func TestCheckMissingBaseline(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	g, out := newGate(dir, false)
	ok, err := g.check(config{profile: "cover.out", base: "main", min: 70, test: "false"})
	if err != nil || !ok || !strings.Contains(out.String(), "baseline unavailable") {
		t.Fatalf("ok = %v, err = %v; want the total comparison skipped\n%s", ok, err, out)
	}
	g, _ = newGate(dir, false)
	_, err = g.check(config{profile: "cover.out", base: "main", min: 70, test: "false", requireBaseline: true})
	if err == nil || !strings.Contains(err.Error(), "measure merge base") {
		t.Fatalf("got %v, want an error with -require-baseline", err)
	}
}

func TestRunExitCodes(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	t.Chdir(dir)
	test := baseFixture(t, basePct50)
	for _, tc := range []struct {
		args []string
		want int
	}{
		{[]string{"-base", "main", "-min", "70", "-test", test}, 0},
		{[]string{"-base", "main", "-min", "80", "-test", test}, 1},
		{[]string{"-base", "origin/nope", "-require-base"}, 2},
		{[]string{"-no-such-flag"}, 2},
	} {
		var out bytes.Buffer
		if got := run(tc.args, &out, io.Discard, func(string) string { return "" }); got != tc.want {
			t.Errorf("run %v = %d, want %d\n%s", tc.args, got, tc.want, out.String())
		}
	}
}
