package main

import (
	"bytes"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The tests in this file run the gate against a real git repository built
// in a temporary directory, with fixture coverage profiles.

// headProfile covers every statement on the feature branch except New.
const headProfile = `mode: set
example.com/m/pkg/a.go:3.14,5.2 1 1
example.com/m/pkg/a.go:7.14,9.2 1 1
example.com/m/pkg/new.go:3.16,5.2 1 1
example.com/m/pkg/new.go:7.16,9.2 1 0
example.com/m/pkg/u.go:3.14,5.2 1 1
example.com/m/pkg/gen.go:3.14,5.2 1 0
example.com/m/pkg/é.go:3.14,5.2 1 1
example.com/m/cmd/x/main.go:3.13,5.2 1 0
`

func gitIn(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	p := filepath.Join(dir, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(p), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

// newRepo makes a repository whose main branch holds pkg/a.go, pkg/old.go
// and cmd/x/main.go. Its git config sets options that would break a naive
// diff parser.
func newRepo(t *testing.T) string {
	t.Helper()
	t.Setenv("GIT_CONFIG_GLOBAL", os.DevNull)
	t.Setenv("GIT_CONFIG_NOSYSTEM", "1")
	for _, k := range []string{"GIT_AUTHOR", "GIT_COMMITTER"} {
		t.Setenv(k+"_NAME", "Test")
		t.Setenv(k+"_EMAIL", "test@example.com")
	}
	dir := t.TempDir()
	gitIn(t, dir, "init", "-q", "-b", "main")
	for _, kv := range [][2]string{{"diff.noprefix", "true"}, {"color.diff", "always"}, {"diff.relative", "true"}} {
		gitIn(t, dir, "config", kv[0], kv[1])
	}
	writeFile(t, dir, ".gitignore", "cover.out\n")
	writeFile(t, dir, "go.mod", "module example.com/m\n")
	writeFile(t, dir, "pkg/a.go", "package pkg\n\nfunc A() int {\n\treturn 1\n}\n")
	writeFile(t, dir, "pkg/old.go", "package pkg\n\nfunc Old() int {\n\treturn 3\n}\n")
	writeFile(t, dir, "cmd/x/main.go", "package main\n\nfunc main() {\n\tprintln()\n}\n")
	gitIn(t, dir, "add", "-A")
	gitIn(t, dir, "commit", "-q", "-m", "base")
	return dir
}

// addFeature branches off main and changes, renames, adds and generates
// files, some committed and some not.
func addFeature(t *testing.T, dir string) {
	t.Helper()
	gitIn(t, dir, "checkout", "-q", "-b", "feature")
	writeFile(t, dir, "pkg/a.go", "package pkg\n\nfunc A() int {\n\treturn 1\n}\n\nfunc B() int {\n\treturn 2\n}\n")
	gitIn(t, dir, "mv", "pkg/old.go", "pkg/new.go")
	writeFile(t, dir, "pkg/new.go", "package pkg\n\nfunc Old() int {\n\treturn 3\n}\n\nfunc New() int {\n\treturn 4\n}\n")
	// A name git C-quotes in diff headers.
	writeFile(t, dir, "pkg/é.go", "package pkg\n\nfunc E() int {\n\treturn 6\n}\n")
	writeFile(t, dir, "cmd/x/main.go", "package main\n\nfunc main() {\n\tprintln(1)\n}\n")
	gitIn(t, dir, "add", "-A")
	gitIn(t, dir, "commit", "-q", "-m", "feature")
	// Untracked, and so new in full.
	writeFile(t, dir, "pkg/u.go", "package pkg\n\nfunc U() int {\n\treturn 5\n}\n")
	writeFile(t, dir, "pkg/gen.go", "// Code generated by hand. DO NOT EDIT.\n\npackage pkg\n\nfunc G() int {\n\treturn 7\n}\n")
	writeFile(t, dir, "cover.out", headProfile)
}

// baseFixture writes a baseline profile and returns a -test command that
// copies it into place.
func baseFixture(t *testing.T, profile string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "base.out")
	writeFile(t, filepath.Dir(p), "base.out", profile)
	return "cp " + p + " {profile}"
}

func newGate(dir string, actions bool) (gate, *bytes.Buffer) {
	var out bytes.Buffer
	return gate{root: dir, out: &printer{w: &out, actions: actions}, stderr: io.Discard}, &out
}

// basePct50 has A covered and Old not: 50%.
const basePct50 = "mode: set\nexample.com/m/pkg/a.go:3.14,5.2 1 1\nexample.com/m/pkg/old.go:3.16,5.2 1 0\n"

func TestCheckMeasuresChangedLinesInARepo(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	test := baseFixture(t, basePct50)
	for _, tc := range []struct {
		min  float64
		want bool
	}{{80, false}, {70, true}} {
		g, out := newGate(dir, false)
		ok, err := g.check(config{profile: "cover.out", base: "main", min: tc.min, test: test})
		if err != nil {
			t.Fatal(err)
		}
		if ok != tc.want {
			t.Errorf("min %.0f: ok = %v, want %v\n%s", tc.min, ok, tc.want, out)
		}
		// a.go 7-9, u.go 3-5 and é.go 3-5 ran; new.go 7-9 did not. cmd/,
		// gen.go and unchanged lines don't count.
		if !strings.Contains(out.String(), "9 of 12 covered") {
			t.Errorf("min %.0f: want 9 of 12 changed lines covered\n%s", tc.min, out)
		}
		if !strings.Contains(out.String(), "merge base") || !strings.Contains(out.String(), "50.00%") {
			t.Errorf("min %.0f: want the 50%% baseline reported\n%s", tc.min, out)
		}
	}
	g, out := newGate(dir, false)
	if _, err := g.check(config{profile: "cover.out", base: "main", min: 80, test: test}); err != nil {
		t.Fatal(err)
	}
	for _, l := range []string{"pkg/new.go:7", "pkg/new.go:8", "pkg/new.go:9"} {
		if !strings.Contains(out.String(), "  "+l+"\n") {
			t.Errorf("want %s listed as uncovered\n%s", l, out)
		}
	}
}

func TestCheckFailsWhenTotalDrops(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	full := "mode: set\nexample.com/m/pkg/a.go:3.14,5.2 1 1\nexample.com/m/pkg/old.go:3.16,5.2 1 1\n"
	g, out := newGate(dir, false)
	ok, err := g.check(config{profile: "cover.out", base: "main", min: 0, test: baseFixture(t, full)})
	if err != nil {
		t.Fatal(err)
	}
	if ok || !strings.Contains(out.String(), "dropped by 16.67 points") {
		t.Fatalf("ok = %v, want a failure for the drop from 100%% to 83.33%%\n%s", ok, out)
	}
}

func TestCheckSkipsWhenNothingChanged(t *testing.T) {
	dir := newRepo(t)
	g, out := newGate(dir, true)
	ok, err := g.check(config{profile: "cover.out", base: "main", min: 80})
	if err != nil || !ok {
		t.Fatalf("ok = %v, err = %v; want a skip", ok, err)
	}
	if !strings.HasPrefix(out.String(), "::warning ") || !strings.Contains(out.String(), "no changes outside documentation and other inert paths") {
		t.Fatalf("want a warning annotation, got %q", out)
	}
}

func TestCheckMissingBase(t *testing.T) {
	dir := newRepo(t)
	g, out := newGate(dir, false)
	ok, err := g.check(config{base: "origin/nope"})
	if err != nil || !ok || !strings.Contains(out.String(), "base origin/nope not found; skipping") {
		t.Fatalf("ok = %v, err = %v, out %q; want a skip", ok, err, out)
	}
	g, _ = newGate(dir, false)
	if _, err := g.check(config{base: "origin/nope", requireBase: true}); err == nil || !strings.Contains(err.Error(), "fetch-depth") {
		t.Fatalf("got %v, want an error with -require-base", err)
	}
}

func TestCheckMissingBaseline(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	g, out := newGate(dir, false)
	ok, err := g.check(config{profile: "cover.out", base: "main", min: 70, test: "false"})
	if err != nil || !ok || !strings.Contains(out.String(), "baseline unavailable") {
		t.Fatalf("ok = %v, err = %v; want the total comparison skipped\n%s", ok, err, out)
	}
	g, _ = newGate(dir, false)
	_, err = g.check(config{profile: "cover.out", base: "main", min: 70, test: "false", requireBaseline: true})
	if err == nil || !strings.Contains(err.Error(), "measure merge base") {
		t.Fatalf("got %v, want an error with -require-baseline", err)
	}
}

func TestRunExitCodes(t *testing.T) {
	dir := newRepo(t)
	addFeature(t, dir)
	t.Chdir(dir)
	test := baseFixture(t, basePct50)
	for _, tc := range []struct {
		args []string
		want int
	}{
		{[]string{"-base", "main", "-min", "70", "-test", test}, 0},
		{[]string{"-base", "main", "-min", "80", "-test", test}, 1},
		{[]string{"-base", "origin/nope", "-require-base"}, 2},
		{[]string{"-no-such-flag"}, 2},
	} {
		var out bytes.Buffer
		if got := run(tc.args, &out, io.Discard, func(string) string { return "" }); got != tc.want {
			t.Errorf("run %v = %d, want %d\n%s", tc.args, got, tc.want, out.String())
		}
	}
	// Errors go to stderr, the report to stdout.
	var out, errOut bytes.Buffer
	run([]string{"-base", "origin/nope", "-require-base"}, &out, &errOut, func(string) string { return "" })
	if !strings.Contains(errOut.String(), "covergate: base origin/nope not found") || out.Len() != 0 {
		t.Fatalf("stdout %q, stderr %q; want the error on stderr only", out.String(), errOut.String())
	}
}

// TestCheckComparesTotalWithoutMeasuredChanges covers changes that touch no
// measured Go line. The total comparison must still run unless every
// changed path is inert, so deleting tests or changing testdata can't lower
// coverage unnoticed.
func TestCheckComparesTotalWithoutMeasuredChanges(t *testing.T) {
	// The baseline covers both A and Old; the head covers only A.
	full := "mode: set\nexample.com/m/pkg/a.go:3.14,5.2 1 1\nexample.com/m/pkg/old.go:3.16,5.2 1 1\n"
	half := "mode: set\nexample.com/m/pkg/a.go:3.14,5.2 1 1\nexample.com/m/pkg/old.go:3.16,5.2 1 0\n"
	drop := []string{"no measured Go lines changed", "dropped by 50.00 points", "FAIL"}
	skip := []string{"no changes outside documentation and other inert paths since merge base", "skipping"}
	files := func(kv ...string) func(*testing.T, string) {
		return func(t *testing.T, dir string) {
			for i := 0; i < len(kv); i += 2 {
				writeFile(t, dir, kv[i], kv[i+1])
			}
		}
	}
	for _, tc := range []struct {
		name      string
		change    func(t *testing.T, dir string)
		untracked bool // leave the change uncommitted and untracked
		profile   string
		want      []string // substrings of the report
		wantOK    bool
	}{
		{
			name:   "tests deleted only",
			change: func(t *testing.T, dir string) { gitIn(t, dir, "rm", "-q", "pkg/old_test.go") },
			want:   drop,
		},
		{name: "go.mod only", change: files("go.mod", "module example.com/m\n\ngo 1.22\n"), want: drop},
		{name: "go.sum only", change: files("go.sum", "example.com/x v1.0.0 h1:abc=\n"), want: drop},
		{name: "untracked nested go.mod", change: files("sub/go.mod", "module example.com/m/sub\n"), untracked: true, want: drop},
		{name: "test file under cmd only", change: files("cmd/x/main_test.go", "package main\n"), want: drop},
		{name: "test file under tools only", change: files("tools/y/y_test.go", "package y\n"), want: drop},
		{name: "testdata only", change: files("testdata/obs.ndjson", "{}\n"), want: drop},
		{name: "workflow only", change: files(".github/workflows/ci.yml", "on: push\n"), want: drop},
		{
			name:    "comment only",
			change:  files("pkg/a.go", "package pkg\n\n// A returns one.\nfunc A() int {\n\treturn 1\n}\n"),
			profile: "mode: set\nexample.com/m/pkg/a.go:4.14,6.2 1 1\nexample.com/m/pkg/old.go:3.16,5.2 1 0\n",
			want:    []string{"none are statements", "dropped by 50.00 points", "FAIL"},
		},
		{
			name: "inert paths only",
			change: files("README.md", "docs\n", "docs/spec/x.md", "spec\n", "docs/adr/x.svg", "<svg/>\n",
				"LICENSE", "license\n", "NOTICE", "notice\n", ".github/reviewers.yml", "x: y\n"),
			want:   skip,
			wantOK: true,
		},
		{name: "untracked doc only", change: files("NOTES.md", "notes\n"), untracked: true, want: skip, wantOK: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := newRepo(t)
			writeFile(t, dir, "pkg/old_test.go", "package pkg\n\nimport \"testing\"\n\nfunc TestOld(t *testing.T) { Old() }\n")
			gitIn(t, dir, "add", "-A")
			gitIn(t, dir, "commit", "-q", "-m", "test Old")
			gitIn(t, dir, "checkout", "-q", "-b", "feature")
			tc.change(t, dir)
			if !tc.untracked {
				gitIn(t, dir, "add", "-A")
				gitIn(t, dir, "commit", "-q", "-m", tc.name)
			}
			profile := tc.profile
			if profile == "" {
				profile = half
			}
			writeFile(t, dir, "cover.out", profile)

			g, out := newGate(dir, false)
			ok, err := g.check(config{
				profile: "cover.out", base: "main", min: 80,
				test: baseFixture(t, full), requireBase: true, requireBaseline: true,
			})
			if err != nil {
				t.Fatal(err)
			}
			if ok != tc.wantOK {
				t.Errorf("ok = %v, want %v", ok, tc.wantOK)
			}
			for _, w := range tc.want {
				if !strings.Contains(out.String(), w) {
					t.Errorf("report lacks %q", w)
				}
			}
			if t.Failed() {
				t.Logf("report:\n%s", out)
			}
		})
	}
}
